name: macOS CI

on: [workflow_dispatch, push, pull_request]

jobs:
  build:
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [ macos-12, macos-11, macos-10.15 ]

    steps:
    - uses: actions/checkout@v3

    - name: Configure
      run: cmake -B ${{github.workspace}}/build

    - name: Build
      run: cmake --build ${{github.workspace}}/build
      env:
        MAKEFLAGS: "-j3"
