name: macOS CI

on: [workflow_dispatch, push, pull_request]

jobs:
  build:
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [ macos-26, macos-15, macos-14 ]

    steps:
    - uses: actions/checkout@v3

    - name: Configure
      run: cmake -B ${{github.workspace}}/build -G Ninja

    - name: Build
      run: cmake --build ${{github.workspace}}/build
      env:
        MAKEFLAGS: "-j3"
